# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: sidebar
  product: ArixoLink Products User Guide
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Overview
    output: web, pdf
    folderitems:

    - title: Get started
      url: /index.html
      output: web, pdf
      type: homepage

    - title: Introduction
      url: /products_introduction.html
      output: web, pdf

    - title: Supported features
      url: /products_supported_features.html
      output: web, pdf

    - title: About the Products
      url: /products_about.html
      output: web, pdf

    - title: Support
      url: /products_support.html
      output: web, pdf

  - title: Release Notes
    output: web, pdf
    folderitems:

    - title: 6.0 Release notes
      url: /products_release_notes_60.html
      output: web, pdf

    - title: 5.0 Release notes
      url: /products_release_notes_50.html
      output: web, pdf

# Copyright 2021 Google LLC
